SETLINESIZE 1000 
  
--DDL OPERATIONS
--TABLES

CREATE TABLE AGENT2 (
  ANO INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE),
  FNAME_LNAME VARCHAR2(60) NOT NULL,
  PASSPORT_NUMBER VARCHAR2(20) NOT NULL,
  TEL_NO VARCHAR2(17),
  CONSTRAINT CH_TELNO_AGENT2 CHECK(
    REGEXP_LIKE(TEL_NO, '^\+375\(\d{2}\)\d{3}-\d{2}-\d{2}$')
  ),
  CONSTRAINT UNI_TELNO_AGENT2 UNIQUE(TEL_NO),
  CONSTRAINT UNI_PASS_NUMBER_AGENT2 UNIQUE(PASSPORT_NUMBER)
);

CREATE TABLE AGENT (
  ANO INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FNAME_LNAME VARCHAR2(60) NOT NULL,
  PASSPORT_NUMBER VARCHAR2(20) NOT NULL,
  TEL_NO VARCHAR2(17),
  CONSTRAINT CH_TELNO_AGENT CHECK(
    REGEXP_LIKE(TEL_NO, '^\+375\(\d{2}\)\d{3}-\d{2}-\d{2}$')
  ),
  CONSTRAINT UNI_TELNO_AGENT2 UNIQUE(TEL_NO),
  CONSTRAINT UNI_PASS_NUMBER_AGENT UNIQUE(PASSPORT_NUMBER)
);

CREATE TABLE OBJECTS (
  ONO INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ONAME VARCHAR2(100) NOT NULL,
  ADDRESS VARCHAR2(60) NOT NULL,
  SQUARE INTEGER NOT NULL,
  PRICE NUMBER(10, 2) NOT NULL,
  FLOORS NUMBER(2, 2),
  COMMENTS VARCHAR2(300),
  VIEW_TIME DATE
);

CREATE TABLE CUSTOMER(
  CNO INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ONAME VARCHAR2(100) NOT NULL,
  FNAME_DIR VARCHAR2(60),
  TEL_NO VARCHAR2(17),
  REQUISITES NVARCHAR2(30),
  REGISTER_NUMBER NUMBER(10, 2),
  CONSTRAINT CH_TELNO_CUSTOMER CHECK(
    REGEXP_LIKE(TEL_NO, '^\+375\(\d{2}\)\d{3}-\d{2}-\d{2}$')
  ),
  CONSTRAINT UNI_TELNO_CUSTOMER UNIQUE(TEL_NO),
  CONSTRAINT UNI_REGISTER_CUSTOMER_ UNIQUE(REGISTER_NUMBER) CONSTRAINT UNI_REQUISITES_CUSTOMER UNIQUE(REQUISITIES)
);

CREATE TABLE SELLER (
  SNO INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ONAME VARCHAR2(100) NOT NULL,
  FNAME_DIR VARCHAR2(60),
  TEL_NO VARCHAR2(17),
  REQUISITES NVARCHAR2(30),
  REGISTER_NUMBER NUMBER(10, 2),
  CONSTRAINT CH_TELNO_SELLER CHECK(
    REGEXP_LIKE(TEL_NO, '^\+375\(\d{2}\)\d{3}-\d{2}-\d{2}$')
  ),
  CONSTRAINT UNI_TELNO_SELLER UNIQUE(TEL_NO) CONSTRAINT UNI_REGISTER_SELLER UNIQUE(REGISTER_NUMBER) CONSTRAINT UNI_REQUESITIES_SELLER UNIQUE(REQUISITES)
);

CREATE TABLE TYPE_OBJECTS (
  TNO INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TYPE VARCHAR2(30)
);

CREATE SYNONYM TYPE FOR TYPE_OBJECTS;

CREATE TABLE DEALS (
  DNO INTEGER GENERATED ALWAYS AS IDENTITY,
  ANO INTEGER NOT NULL,
  SNO INTEGER NOT NULL,
  CNO INTEGER NOT NULL,
  ONO INTEGER,
  TNO INTEGER NOT NULL,
  DATE1 DATE NOT NULL,
  PRICE NUMBER (10, 2) NOT NULL,
  FNAME_LNAME_NOTARY VARCHAR(60),
  COMMENT1 VARCHAR2(300),
  PRIMARY KEY(DNO),
  CONSTRAINT ANO_FK_DEALS FOREIGN KEY(ANO) REFERENCES AGENT,
  CONSTRAINT SNO_FK_DEALS FOREIGN KEY(SNO) REFERENCES SELLER,
  CONSTRAINT CNO_FK_DEALS FOREIGN KEY(CNO) REFERENCES CUSTOMER,
  CONSTRAINT ONO_FK_DEALS FOREIGN KEY(ONO) REFERENCES OBJECTS1,
  CONSTRAINT TNO_FK_DEALS FOREIGN KEY(TNO) REFERENCES TYPE_OBJECTS
);

--SEQUENCES

CREATE SEQUENCE AGENT_SEQ MINVALUE 1 MAXVALUE 9999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE OBJECTS1_SEQ MINVALUE 1 MAXVALUE 9999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE CUSTOMER_SEQ MINVALUE 1 MAXVALUE 9999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SELLER_SEQ MINVALUE 1 MAXVALUE 9999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE TYPE_OBJECTS_SEQ MINVALUE 1 MAXVALUE 9999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE DEALS_SEQ MINVALUE 1 MAXVALUE 9999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;

--INDEX
CREATE INDEX DEALSANO ON DEALS (ANO);

--ALTERING TABLE

ALTER TABLE
  OBJECTS1
MODIFY
  PRICE (NUMBER(10, 2));

GENERATED ALWAYS AS IDENTITY 

--DML OPERATIONS

--INSERTING

INSERT INTO
  AGENT (FNAME_LNAME, PASSPORT_NUMBER, TEL_NO)
VALUES
  (
    'Еркен Мирас',
    'N705010',
    '+375(29)221-11-71'
  );

INSERT INTO
  AGENT (FNAME_LNAME, PASSPORT_NUMBER, TEL_NO)
VALUES
  (
    'Бердибаев Еркин',
    'N301050',
    '+375(29)221-11-72'
  );

INSERT INTO
  AGENT (FNAME_LNAME, PASSPORT_NUMBER, TEL_NO)
VALUES
  (
    'Назымбеков Адилет',
    'N200504',
    '+375(29)221-11-73'
  );

INSERT INTO
  AGENT (FNAME_LNAME, PASSPORT_NUMBER, TEL_NO)
VALUES
  (
    'Кошенов Айдын',
    'N220114',
    '+375(29)221-11-74'
  );

INSERT INTO
  AGENT (FNAME_LNAME, PASSPORT_NUMBER, TEL_NO)
VALUES
  (
    'Кайыргельдинов Бахтияр',
    'N440440',
    '+375(29)221-11-75'
  );

INSERT INTO
  OBJECTS1 (
    ONAME,
    ADDRESS,
    SQUARE,
    PRICE,
    FLOORS,
    COMMENTS
  )
VALUES
  (
    'Магазин одежды Башмачок',
    'Ул. Мангилик ел 54/1',
    '400m^2',
    '40000',
    '1',
    'no comments'
  );

INSERT INTO
  OBJECTS1 (
    ONAME,
    ADDRESS,
    SQUARE,
    PRICE,
    FLOORS,
    COMMENTS
  )
VALUES
  (
    'Деловой дом "Алма-Ата"',
    'Ул. Иманова 49/1',
    '9000m^2',
    '900000',
    '5',
    'no comments'
  );

INSERT INTO
  OBJECTS1 (
    ONAME,
    ADDRESS,
    SQUARE,
    PRICE,
    FLOORS,
    COMMENTS
  )
VALUES
  (
    'Ресторан "Бахчисарай"',
    'Ул. Аблай-хана 11',
    '500m^2',
    '500000',
    '2',
    'no comments'
  );

INSERT INTO
  OBJECTS1 (
    ONAME,
    ADDRESS,
    SQUARE,
    PRICE,
    FLOORS,
    COMMENTS
  )
VALUES
  (
    'Кафе "Кофемолка"',
    'Ул. Жирентаева 15/1',
    '200m^2',
    '60000',
    '1',
    'no comments'
  );

INSERT INTO
  OBJECTS1 (
    ONAME,
    ADDRESS,
    SQUARE,
    PRICE,
    FLOORS,
    COMMENTS
  )
VALUES
  (
    'Магазин электроники "Сулпак"',
    'Ул. Сауран 15',
    '350m^2',
    '100000',
    '1',
    'no comments'
  );

INSERT INTO
  OBJECTS1 (
    ONAME,
    ADDRESS,
    SQUARE,
    PRICE,
    FLOORS,
    COMMENTS
  )
VALUES
  (
    'Супермаркет "Magnum"',
    'Ул. Момышулы 33',
    '270m^2',
    '30000',
    '2',
    'no comments'
  );

INSERT INTO
  OBJECTS1 (
    ONAME,
    ADDRESS,
    SQUARE,
    PRICE,
    FLOORS,
    COMMENTS
  )
VALUES
  (
    'Бизнес центр "Миллионер"',
    'Ул. Мангилик ел 33',
    '5000m^2',
    '999999',
    '10',
    'no comments'
  );

INSERT INTO
  OBJECTS1 (
    ONAME,
    ADDRESS,
    SQUARE,
    PRICE,
    FLOORS,
    COMMENTS
  )
VALUES
  (
    'Лаунч-бар "Мята"',
    'Ул. Кабанбай батыра 1',
    '100m^2',
    '10000',
    '1',
    'no comments'
  );

INSERT INTO
  OBJECTS1 (
    ONAME,
    ADDRESS,
    SQUARE,
    PRICE,
    FLOORS,
    COMMENTS
  )
VALUES
  (
    'Рестобар "Аура"',
    'Ул. 188 здание 4',
    '150m^2',
    '15000',
    '2',
    'no comments'
  );

INSERT INTO
  OBJECTS1 (
    ONAME,
    ADDRESS,
    SQUARE,
    PRICE,
    FLOORS,
    COMMENTS
  )
VALUES
  (
    'Кондитерская "Татти"',
    'Ул. Сыганак 18/1',
    '70m^2',
    '7.000',
    '3',
    'no comments'
  );

INSERT INTO
  OBJECTS1 (
    ONAME,
    ADDRESS,
    SQUARE,
    PRICE,
    FLOORS,
    COMMENTS
  )
VALUES
  (
    'Ангар',
    'Ул. 40 станция',
    '1000m^2',
    '500000',
    '1',
    'no comments'
  );

INSERT INTO
  TYPE
VALUES
  (TYPE_OBJECTS_SEQ.NEXTVAL, 'Офис');

INSERT INTO
  TYPE
VALUES
  (TYPE_OBJECTS_SEQ.NEXTVAL, 'Павильон');

INSERT INTO
  TYPE
VALUES
  (
    TYPE_OBJECTS_SEQ.NEXTVAL,
    'Рабочий участок'
  );

INSERT INTO
  TYPE
VALUES
  (TYPE_OBJECTS_SEQ.NEXTVAL, 'Склад');

INSERT INTO
  TYPE
VALUES
  (
    TYPE_OBJECTS_SEQ.NEXTVAL,
    'Торговый зал');

INSERT INTO
  TYPE
VALUES
  (TYPE_OBJECTS_SEQ.NEXTVAL, 'Помещение');

INSERT INTO
  SELLER
VALUES
  (
    SELLER_SEQ.NEXTVAL,
    'ASTEL',
    'Адырбаева Алтынай',
    '+375(29)225-12-71',
    'KZ3334445555',
    '45632178'
  );

INSERT INTO
  SELLER
VALUES
  (
    SELLER_SEQ.NEXTVAL,
    'AltynEx',
    'Маштеева Дария',
    '+375(29)225-13-71',
    'KZ1214562132',
    '25056105'
  );

INSERT INTO
  SELLER
VALUES
  (
    SELLER_SEQ.NEXTVAL,
    'Altyntau Kokshetau',
    'Толегенова Менсулу',
    '+375(29)225-14-71',
    'KZ0456156565',
    '10651056'
  );

INSERT INTO
  SELLER
VALUES
  (
    SELLER_SEQ.NEXTVAL,
    'Актюбинский завод нефтяного оборудования',
    'Толегенова Лаура',
    '+375(29)225-15-71',
    'KZ0565156040',
    '55555555'
  );

INSERT INTO
  SELLER
VALUES
  (
    SELLER_SEQ.NEXTVAL,
    'БАСТ',
    'Султан Нурболат',
    '+375(29)225-16-71',
    'KZ3334445555',
    '45632178'
  );

INSERT INTO
  SELLER
VALUES
  (
    SELLER_SEQ.NEXTVAL,
    'BCC Invest',
    'Бигожин Рысдаулет',
    '+375(29)225-17-71',
    'KZ0561654050',
    '15601560'
  );

INSERT INTO
  SELLER
VALUES
  (
    SELLER_SEQ.NEXTVAL,
    'ГРК Бенкала',
    'Акжигит Нурсезим',
    '+375(29)225-18-71',
    'KZ0561256156',
    '50468488'
  );

INSERT INTO
  SELLER
VALUES
  (
    SELLER_SEQ.NEXTVAL,
    'Батыс Транзит',
    'Шопанова Салтанат',
    '+375(29)225-19-71',
    'KZ0456158900',
    '10654600'
  );

INSERT INTO
  SELLER
VALUES
  (
    SELLER_SEQ.NEXTVAL,
    'НУХ "Baiterek',
    'Шопанов Ильяс',
    '+375(29)225-20-71',
    'KZ1560465123',
    '15604868'
  );

INSERT INTO
  SELLER
VALUES
  (
    SELLER_SEQ.NEXTVAL,
    'Банк ВТБ Казахстан',
    'Иманжусупов Даурен',
    '+375(29)225-21-71',
    'KZ4015641560',
    '35015600'
  );

INSERT INTO
  SELLER
VALUES
  (
    SELLER_SEQ.NEXTVAL,
    'Банк ЦентрКредит',
    'Калдыбек Аружан',
    '+375(29)225-22-71',
    'KZ0151560135',
    '45861231'
  );

INSERT INTO
  SELLER
VALUES
  (
    SELLER_SEQ.NEXTVAL,
    'Кристалл Менеджмент',
    'Токпанова Динара',
    '+375(29)225-23-71',
    'KZ0454564055',
    '15605601'
  );

/
INSERT INTO
  CUSTOMER
VALUES
  (
    CUSTOMER_SEQ.NEXTVAL,
    'ТОО "Айдала Мунай"',
    'Шопанов Жаксыбай',
    '+375(29)225-55-71',
    'KZ70070123321',
    '55456456'
  );

INSERT INTO
  CUSTOMER
VALUES
  (
    CUSTOMER_SEQ.NEXTVAL,
    'AO "AMF Group"',
    'Амербеков Кадыр-хан',
    '+375(29)225-56-71',
    'KZ12314564765',
    '12355644'
  );

INSERT INTO
  CUSTOMER
VALUES
  (
    CUSTOMER_SEQ.NEXTVAL,
    'АО "Акжал Голд Ресорсиз"',
    'Саламатов Алишер',
    '+375(29)225-57-71',
    'KZ51234685565',
    '45123880'
  );

INSERT INTO
  CUSTOMER
VALUES
  (
    CUSTOMER_SEQ.NEXTVAL,
    'АстанаГаз КМГ',
    'Нуржанов Жандос',
    '+375(29)225-88-71',
    'KZ70702156654',
    '89126440'
  );

INSERT INTO
  CUSTOMER
VALUES
  (
    CUSTOMER_SEQ.NEXTVAL,
    'АО "Казахалтын"',
    'Хотько Анастасия',
    '+375(29)225-59-71',
    'KZ45648158655',
    '46545850'
  );

INSERT INTO
  CUSTOMER
VALUES
  (
    CUSTOMER_SEQ.NEXTVAL,
    'Алматытемир',
    'Койшикарин Рустам',
    '+375(29)225-60-71',
    'KZ45614846488',
    '45622270'
  );

INSERT INTO
  CUSTOMER
VALUES
  (
    CUSTOMER_SEQ.NEXTVAL,
    'АлмаТел Казахстан',
    'Сейтпенбетов Жанболат',
    '+375(29)225-61-71',
    'KZ04515315515',
    '51117560'
  );

INSERT INTO
  CUSTOMER
VALUES
  (
    CUSTOMER_SEQ.NEXTVAL,
    'Алтай Ресорсиз',
    'Рахатулы Алишер',
    '+375(29)225-62-71',
    'KZ55445456250',
    '65454480'
  );

INSERT INTO
  CUSTOMER
VALUES
  (
    CUSTOMER_SEQ.NEXTVAL,
    'Актобемунайгаз',
    'Жуматай Гульдана',
    '+375(29)225-63-71',
    'KZ11156515611',
    '45648120'
  );

INSERT INTO
  CUSTOMER
VALUES
  (
    CUSTOMER_SEQ.NEXTVAL,
    'ForteBank',
    'Рысбекулы Бекзат',
    '+375(29)225-64-71',
    'KZ45015612123',
    '56645650'
  );

INSERT INTO
  CUSTOMER
VALUES
  (
    CUSTOMER_SEQ.NEXTVAL,
    'Азиятский банк развития',
    'Жанасбай Арсен',
    '+375(29)225-65-71',
    'KZ07072224566',
    '45488820'
  );

INSERT INTO
  CUSTOMER
VALUES
  (
    CUSTOMER_SEQ.NEXTVAL,
    'АТФБанк',
    'Аргинова Айнур',
    '+375(29)225-66-71',
    'KZ05561156156',
    '56165550'
  );


BEGIN
INSERT INTO
  DEALS (
    ANO,
    SNO,
    CNO,
    ONO,
    TNO,
    DATE1,
    PRICE,
    FNAME_LNAME_NOTARY,
    COMMENT1
  )
VALUES
  (
    '43',
    '42',
    '96',
    '2',
    '4',
    TO_DATE('03.04.21', 'dd.mm.yy'),
    '40.000',
    'Аманов Рауан',
    'no comments'
  );

INSERT INTO
  DEALS (
    ANO,
    SNO,
    CNO,
    ONO,
    TNO,
    DATE1,
    PRICE,
    FNAME_LNAME_NOTARY,
    COMMENT1
  )
VALUES
  (
    '45',
    '50',
    '92',
    '11',
    '4',
    TO_DATE('03.05.19', 'dd.mm.yy'),
    '500.000',
    'Каиров Расул',
    'no comments'
  );

INSERT INTO
  DEALS (
    ANO,
    SNO,
    CNO,
    ONO,
    TNO,
    DATE1,
    PRICE,
    FNAME_LNAME_NOTARY,
    COMMENT1
  )
VALUES
  (
    '41',
    '46',
    '94',
    '10',
    '5',
    TO_DATE('29.10.21', 'dd.mm.yy'),
    '7.000',
    'Шафихов Шапагат',
    'no comments'
  );

INSERT INTO
  DEALS (
    ANO,
    SNO,
    CNO,
    ONO,
    TNO,
    DATE1,
    PRICE,
    FNAME_LNAME_NOTARY,
    COMMENT1
  )
VALUES
  (
    '43',
    '53',
    '102',
    '6',
    '3',
    TO_DATE('29.10.20', 'dd.mm.yy'),
    '30.000',
    'Хамед Байразадех',
    'no comments'
  );

INSERT INTO
  DEALS (
    ANO,
    SNO,
    CNO,
    ONO,
    TNO,
    DATE1,
    PRICE,
    FNAME_LNAME_NOTARY,
    COMMENT1
  )
VALUES
  (
    '42',
    '52',
    '98',
    '7',
    '1',
    TO_DATE('29.10.20', 'dd.mm.yy'),
    '999.999',
    'Адильханова Аида',
    'no comments'
  );

INSERT INTO
  DEALS (
    ANO,
    SNO,
    CNO,
    ONO,
    TNO,
    DATE1,
    PRICE,
    FNAME_LNAME_NOTARY,
    COMMENT1
  )
VALUES
  (
    '43',
    '51',
    '88',
    '4',
    '6',
    TO_DATE('28.10.21', 'dd.mm.yy'),
    '60.000',
    'Мелдеев Усен',
    'no comments'
  );

INSERT INTO
  DEALS (
    ANO,
    SNO,
    CNO,
    ONO,
    TNO,
    DATE1,
    PRICE,
    FNAME_LNAME_NOTARY,
    COMMENT1
  )
VALUES
  (
    '44',
    '47',
    '82',
    '8',
    '6',
    TO_DATE('28.10.21', 'dd.mm.yy'),
    '10.000',
    'Сагынгалиев Ернур',
    'no comments'
  );

INSERT INTO
  DEALS (
    ANO,
    SNO,
    CNO,
    ONO,
    TNO,
    DATE1,
    PRICE,
    FNAME_LNAME_NOTARY,
    COMMENT1
  )
VALUES
  (
    '43',
    '49',
    '90',
    '2',
    '1',
    TO_DATE('28.10.21', 'dd.mm.yy'),
    '40.000',
    'Жаксылыкова Дильназ',
    'no comments'
  );

INSERT INTO
  DEALS (
    ANO,
    SNO,
    CNO,
    ONO,
    TNO,
    DATE1,
    PRICE,
    FNAME_LNAME_NOTARY,
    COMMENT1
  )
VALUES
  (
    '45',
    '42',
    '102',
    '3',
    '4',
    TO_DATE('14.12.21', 'dd.mm.yy'),
    '50.000',
    'Жаксылыкова Дильназ',
    'no comments'
  );

END;

--PL/SQL BLOCK
--Triggers

/ CREATE
OR REPLACE TRIGGER SEQ_AGENT BEFORE
INSERT
  ON AGENT FOR EACH ROW BEGIN
SELECT
  AGENT_SEQ.NEXTVAL INTO :NEW.ANO
FROM
  DUAL;

END SEQ_AGENT;

CREATE
OR REPLACE TRIGGER SEQ_OBJECTS1 BEFORE
INSERT
  ON OBJECTS1 FOR EACH ROW BEGIN
SELECT
  OBJECTS1_SEQ.NEXTVAL INTO :NEW.ONO
FROM
  DUAL;

END SEQ_OBJECTS1;

CREATE
OR REPLACE TRIGGER SEQ_CUSTOMER BEFORE
INSERT
  ON CUSTOMER FOR EACH ROW BEGIN
SELECT
  CUSTOMER_SEQ.NEXTVAL INTO :NEW.CNO
FROM
  DUAL;

END SEQ_CUSTOMER;

CREATE
OR REPLACE TRIGGER SEQ_DEALS BEFORE
INSERT
  ON DEALS FOR EACH ROW BEGIN
SELECT
  DEALS_SEQ.NEXTVAL INTO :NEW.DNO
FROM
  DUAL;

END SEQ_DEALS

--INSERT ALL

INSERT
  ALL INTO AGENT2 (ANO, FNAME_LNAME, PASSPORT_NUMBER, TEL_NO)
VALUES
  (
    '1',
    'Еркен Мирас',
    'N705010',
    '+375(29)221-11-71'
  ) INTO AGENT2 (ANO, FNAME_LNAME, PASSPORT_NUMBER, TEL_NO)
VALUES
  (
    '2',
    'Бердибаев Еркин',
    'N301050',
    '+375(29)221-11-72'
  ) INTO AGENT2 (ANO, FNAME_LNAME, PASSPORT_NUMBER, TEL_NO)
VALUES
  (
    '3',
    'Назымбеков Адилет',
    'N200504',
    '+375(29)221-11-73'
  ) INTO AGENT2 (ANO, FNAME_LNAME, PASSPORT_NUMBER, TEL_NO)
VALUES
  (
    '4',
    'Кошенов Айдын',
    'N220114',
    '+375(29)221-11-74'
  ) INTO AGENT2 (ANO, FNAME_LNAME, PASSPORT_NUMBER, TEL_NO)
VALUES
  (
    '5',
    'Кайыргельдинов Бахтияр',
    'N440440',
    '+375(29)221-11-75'
  )
SELECT
  *
FROM
  DUAL;