CREATE USER DUMMY IDENTIFIED BY DUMB DEFAULT TABLESPACE USERS QUOTA 100M ON USERS TEMPORARY TABLESPACE TEMP QUOTA 10M ON TEMP DEFAULT TABLESPACE JOHNY_TABSPACE TEMPORARY TABLESPACE JOHNY_TABSPACE_TEMP;

GRANT ALTER ANY TABLE TO C##KUKAZHK;

GRANT ALTER ANY PROCEDURE TO C##KUKAZHK;

GRANT ALTER ANY TRIGGER TO C##KUKAZHK;

GRANT ALTER PROFILE TO C##KUKAZHK;

GRANT DELETE ANY TABLE TO C##KUKAZHK;

GRANT DROP ANY TABLE TO C##KUKAZHK;

GRANT DROP ANY PROCEDURE C##KUKAZHK;

GRANT DROP ANY TRIGGER C##KUKAZHK;

GRANT DROP ANY VIEW C##KUKAZHK;

GRANT DROP PROFILE C##KUKAZHK;

DROP TABLE VIEWING;

DROP TABLE RENTER;